server:
  port: 8085
  ssl:
    enabled: false
    key-store: classpath:keystore/baeldung.p12
    key-store-password: password
    key-alias: baeldung
    key-store-type: PKCS12
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: tickets
          uri: http://localhost:8080
          predicates:
            - Path=/tickets/**
          filters:
            - RewritePath=/tickets(?<segment>/?.*), $\{segment}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8661/eureka/
  instance:
    hostname: localhost
    instance-id: gateway

management:
  endpoints:
    web:
      exposure:
        include: 'gateway'