server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: test
#          uri: lb://booking-service/
#          predicates:
#            - Path=/test/**
#          filters:
#            - RewritePath=/booking-service(?<segment>/?.*), $\{segment}
#          metadata:
#            management.port: 8083
        - id: tickets
          uri: http://localhost:8080
          predicates:
            - Path=/tickets/**
          filters:
            - RewritePath=/tickets(?<segment>/?.*), $\{segment}
#          metadata:
#            management-port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8661/eureka/
  instance:
    hostname: localhost
    instance-id: gateway

management:
  endpoints:
    web:
      exposure:
        include: 'gateway'