server:
  port: 8085
spring:
  application:
    name: booking-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8661/eureka
  instance:
    hostname: localhost