version: "3.9"
services:
  spring:
    container_name: spring
    privileged: true
    hostname: spring
    image: spring-image:latest
    networks:
      - dummy_network
    ports:
      - "8081:8081"

  jax_rs:
    container_name: jax_rs
    hostname: jax_rs
    image: jax_rs-image:latest
    networks:
      - dummy_network
    ports:
      - "8080:8080"

networks:
  dummy_network:
    driver: bridge