spring:
  application:
    name: ticket_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-a91wke62kjgj13zf.mdb.yandexcloud.net:6432/makarov-n?targetServerType=master&ssl=true&sslmode=verify-full&currentSchema=soa
    username: nmakarov
    password: makarovnurgun
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
#  cloud:
#    consul:
#      port: 8500
#      host: localhost
#      discovery:
#        instance-id: ticket_service_i1
server:
  port: 8081
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/client.keystore
#    key-store-password: secret
#    key-store-provider: SUN
#    trust-store: classpath:keystore/client.truststore
#    trust-store-password: secret
#management:
#  server:
#    ssl:
#      enabled: true
#      key-store: classpath:keystore/client.keystore
#      key-store-password: secret
#      trust-store: classpath:keystore/client.truststore
#      trust-store-password: secret
#    port: 840